import { Certification } from "./certification.type";
import { Education } from "./education.type";
import { Experience } from "./experience.type";

export interface Candidate {
    id: string;
    first_name: string;
    middle_name: string;
    last_name: string;
    display_name: string;
    phone: number;
    alt_phone: number;
    email: string;
    alt_email: string;
    gender: string;
    current_ctc: number;
    expected_ctc: number;
    notice_period: string;
    total_exp: number;
    relavant_exp: number;
    location: string;
    preffered_location: string[];
    date_of_birth: string;
    current_organisation: string;
    education: Education[];
    experience: Experience[];
    certification: Certification[];
    linkedin_id: string;
    resume: string;
    document_type: string[];
    document: string;
    document_number: string;
    issue_date: string;
    expiry_date: string;
    source_type: string;
    source_name: string;
    preffered_job: string[];
    candidate_picture: string;
    uan_number: string;
    comments: string;
    pan_number: string;
    PreferredJob: string;
    skillset: string[];
    secondary_skill_set: string[];
}